export default {
    SET_CITIES_FOUND: 'SET_CITIES_FOUND',
    REMOVE_CITIES_FOUND: 'REMOVE_CITIES_FOUND',
    ADD_CITY_ID: 'ADD_CITY_ID',
    ADD_FAVORITES_CITY: 'ADD_FAVORITES_CITY',
    REMOVE_CITY_ID: 'REMOVE_CITY_ID',
    REMOVE_CITY_FAVORITES: 'REMOVE_CITY_FAVORITES',
    SET_CITIES_IDS: 'SET_CITIES_IDS',
    SET_FAVORITES_CITIES: 'SET_FAVORITES_CITIES',
    GET_USER_LOCATION: 'GET_USER_LOCATION',
    SUCCESS_LOAD_USER_LOCATION: 'SUCCESS_LOAD_USER_LOCATION',
    ERROR_LOAD_USER_LOCATION: 'ERROR_LOAD_USER_LOCATION'
};
